server:
  port: 8081
spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC
    username: test
    password: 1234


#mybatis:
#  config-location: classpath:config/config.xml
#  mapper-location: classpath:mapper/*.xml

#yml yaml
#server.port=8081
#spring.devtools.restart.enabled=true
#spring.devtools.restart.additional-exclude=static/**
